baseURL = "https://example.com"
title = "Thoughts from Daniel P."
author = "Daniel P. Riggins"
theme = "hugo-theme-m10c"
paginate = 5
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  author = "Daniel P. Riggins"
  description = "A 30-something pediatric resident in Indianapolis, IN"
  avatar = "https://i.postimg.cc/449YxySF/me.jpg"
  [[params.social]]
    name = "github"
    url = "https://github.com/andtheWings"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/danriggins"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
