---
title: Prevention on my mind
author: "Daniel P. Riggins"
date: "`r Sys.Date()`"
slug: prevention-on-my-mind
categories: []
tags: [intro]
---

Hi, I'm Dan. I'm a pediatric resident at [Riley Hospital for Children](https://www.instagram.com/rileychildrens/). I spent my last month in our intensive care unit, which was a humbling experience in a few different ways. First in terms of how much medicine I still have to learn after 6+ years of education/training. Also in terms of the awesome power we healthcare providers have to sustain our patients' lives. But finally, how limited we are to alter the overall life course of most children.

Let's drill into this last point a little more. Even with a catchment area that covers almost all of Indiana and with tens of thousands of encounters a year, we only see a fraction of our state's population. Furthermore, we are really good at keeping sick children alive, but we are less equipped to keep them from getting sick/hurt in the first place. Just this month, I have seen a 1st grader who was struck almost dirctly by a vehicle that T-boned his family's car, a toddler that was shaken so hard by his frustrated parent he ultimately died of brain damage, and a newborn who's body was ravaged by a metabolic disorder that screening tests identified only hours after he presented to our unit. We can use machines to breathe for these children, filter their blood, and even bypass the beating of their heart for a time, but the damage is already done.